### ISSUE TITLE
Cookie\Guard expects Illuminate\Encryption\Encrypter

### ISSUE THREAD

**Issue by jeffmikels** [tomgrohl/laravel4-php71-encrypter#11]
I'm getting this error.

Type error: Argument 2 passed to Illuminate\Cookie\Guard::__construct() must be an instance of Illuminate\Encryption\Encrypter, instance of Tomgrohl\Laravel\Encryption\Encrypter given

Can anyone help me?

**Comment by tomgrohl** [comment]
The encrypter extends laravels so you shouldn't be getting this error. What version are you running?

**Comment by hugossvoboda** [comment]
I have the same error after completed the step 2:

ErrorException (E_RECOVERABLE_ERROR)
HELP
Argument 2 passed to Illuminate\Cookie\Guard::__construct() must be an instance of Illuminate\Encryption\Encrypter, instance of Tomgrohl\Laravel\Encryption\Encrypter given

I have already updated the Laravel version from 4.1 to 4.2.
PHP version: 5.6.30

Could you help me, please?

**Comment by tomgrohl** [comment]
Make sure you're using version 1.1 and not the dev-master branch.
