### ISSUE TITLE
Unable to get this working

### ISSUE THREAD

**Issue by iamface** [tomgrohl/laravel4-php71-encrypter#14]
Sorry for posting as an issue, but I'm unable to get this to work, I'm still just seeing "Mcrypt PHP extension required."

I've added this package and updated composer. I added the provider and changed the cypher but no dice.. I even tried the steps at https://medium.com/@ysbilgin/running-laravel-4-2-project-on-php-7-3-or-7-4-b18e41caa0b

PHP version - 7.4.4
composer.json - 
"require": {
                "laravel/framework": "4.2.22",
                "tomgrohl/laravel4-php71-encrypter": "^1.1"
        },

I've tried adding extension=mcrypt.so to my php.ini even.

Any suggestions one what I might be mssing?

**Comment by lukaszradziak** [comment]
@iamface did you find the solution?

**Comment by iamface** [comment]
@lukasilestam I did not, and haven't come back to that project yet :/

**Comment by tomgrohl** [comment]
Sorry for the delay. I've not been working on any personal projects in a while. 

As this issue doesn't relate to a bug with this library I'll close it. 

If the mcrypt extension is correctly loaded then it should work. Running phpinfo() would also show if mcrypt is running. 

You may also need to reload php-fpm or apache.
