### ISSUE TITLE
Unable to use cipher AES-256-CBC

### ISSUE THREAD

**Issue by lieusq** [tomgrohl/laravel4-php71-encrypter#15]
Hi,

Shouldn't you also pass the $cipher variable to the parent construct as well? If not it will be using the default cipher which is AES-128-CBC since no variable was pass 
![image](https://user-images.githubusercontent.com/37057921/120480655-deec0600-c3e1-11eb-9459-e10becb6c445.png)

**Comment by tomgrohl** [comment]
![Screenshot_20210602-183822_Chrome](https://user-images.githubusercontent.com/418838/120527395-32eeee80-c3d2-11eb-9f52-2bcbc6bf006f.jpg)

The laravel encrypter only allows a key to be passed in the constructor. Which is why after the parent call the cipher is being overridden (line 27).

**Comment by lieusq** [comment]
Maybe can state that version 5.0 Illuminate\Encryption\Encrypter and below was used as anything newer it does pass $cipher in the construct 


![image](https://user-images.githubusercontent.com/37057921/120581577-a25df000-c45d-11eb-8377-d0669dc7f64a.png)
