### ISSUE TITLE
Alias in EncryptionServiceProvider

### ISSUE THREAD

**Issue by berndlosert** [tomgrohl/laravel4-php71-encrypter#2]
I believe you have the argument order backwards: https://github.com/tomgrohl/laravel4-php71-encrypter/blob/1.1/src/Tomgrohl/Laravel/Encryption/EncryptionServiceProvider.php#L31. It should be

```php
$this->app->alias('encrypter', Encrypter::class);
```

**Comment by tomgrohl** [comment]
Oh dear don't know how I managed that. Thats now fixed in version 1.1.1.

Thanks
