### ISSUE TITLE
Exception thrown when key length is 32

### ISSUE THREAD

**Issue by berndlosert** [tomgrohl/laravel4-php71-encrypter#3]
If you set the cipher to be AES-256-CBC and update the key so that it has 32 characters, then the code in https://github.com/tomgrohl/laravel4-php71-encrypter/blob/1.1/src/Tomgrohl/Laravel/Encryption/EncryptionServiceProvider.php#L18 will throw an exception since you're calling `new Encrypter()` without setting the cipher. I suggest changing the logic to this to fix this problem:

```php
            if ($app['config']->has('app.cipher')) {
                $encrypter = new Encrypter(
                    $app['config']['app.key'],
                    $app['config']['app.cipher']
                );
            } else {
                $encrypter = new Encrypter($app['config']['app.key']);
            }
```

**Comment by tomgrohl** [comment]
Thanks for reporting. Fixed in 1.1.2
