### ISSUE TITLE
registerCoreContainerAliases() problem

### ISSUE THREAD

**Issue by berndlosert** [tomgrohl/laravel4-php71-encrypter#4]
Laravel will automatically alias its own encrypter here: https://github.com/laravel/framework/blob/4.2/src/Illuminate/Foundation/Application.php#L1116, which it needs e.g. here https://github.com/laravel/framework/blob/4.2/src/Illuminate/Foundation/Application.php#L658. Without overridding this, I run into strange issues like e.g. unit tests failing in my project. I don't know if there's a clean way of overridding this though.

**Comment by tomgrohl** [comment]
My service provider should override the alias. Are you adding your service provider to the end of the service providers array in the app.php config?

Laravel 4 does make it hard to override their components.

**Comment by berndlosert** [comment]
> Are you adding your service provider to the end of the service providers array in the app.php config?

Yes. I think the problem comes from the fact that before that array is processed, Laravel is already using the encrypter alias somewhere.

**Comment by tomgrohl** [comment]
I can't currently test it but can you try moving the service provider in the app config under `'Illuminate\Encryption\EncryptionServiceProvider',` and then commenting out Laravels.

**Comment by tomgrohl** [comment]
So I installed the latest version (1.1.2) in a laravel 4.2.22 setup and made the following changes in app config:

```
//'Illuminate\Encryption\EncryptionServiceProvider', 

\Tomgrohl\Laravel\Encryption\EncryptionServiceProvider::class,
```

The app boots fine. Added a test that uses my encrypter and it ran fine.

Let me know if you have any issues still.

**Comment by berndlosert** [comment]
After some more testing, it seems that I don't have to override `registerCoreContainerAliases()` as I initially thought. Closing issue.
