### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by overrider** [tomgrohl/laravel4-php71-encrypter#5]
Hello there,

could this be made run with PHP 7.2 as well?

thanks...

**Comment by tomgrohl** [comment]
Hi. 

As far as I'm aware it should work. I don't have a Laravel 4.2 with PHP 7.2 setup to test.

Feel free to try it out and get back to me if it doesn't.

Thanks

**Comment by overrider** [comment]
Yes it works. Here is what i did to my Laravel 4.2 / PHP7.2 installation 

Step 1:
Follow your README.md, but the line i added to the providers read 
'\Tomgrohl\Laravel\Encryption\EncryptionServiceProvider' , not like in the README

Step 2:
Open vendor/laravel/framework/src/Illuminate/Foundation/start.php and comment out the if statement on line 27 that checks for mcrypt extension being available

Step 3:
Open vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php and set the $cipher and $mode variable to be ""

Works without Errors, thanks!

**Comment by tomgrohl** [comment]
Just as an FYI. Running composer install/update could wipe the change you make.

To get around this issue you could install the mcrypt extension, even though it wouldn't be used. 

In PHP 7.2 mcrypt was removed but can be installed using pecl.

**Comment by weotch** [comment]
I published a fork with these changes: https://github.com/weotch/framework/commit/420db5f6993a9ad5faaeb964e690bd0636f6440f

You can use in your project like:

```json
{
	"require": {
		"laravel/framework": "dev-4.2-for-php7.4 as 4.2.22",
	},
	"repositories": [
		{
			"type": "vcs",
			"url": "git@github.com:weotch/framework.git"
		}
	],
}
```
