### ISSUE TITLE
Still a problem with Artisan?

### ISSUE THREAD

**Issue by asdf072** [tomgrohl/laravel4-php71-encrypter#6]
Using your encryptor solved my problems with webserver access, but any cli call to artisan still gives me 'Mcrypt PHP extension required.' Is there a workaround for that?

**Comment by tomgrohl** [comment]
Looks like this is hard coded in `Illuminate/Foundation/start.php`

```

if ( ! extension_loaded('mcrypt'))
{
	echo 'Mcrypt PHP extension required.'.PHP_EOL;
	exit(1);
}
```

To get around this issue you would have to install the mcrypt extension, even though it wouldn't be used. 

In PHP 7.2 mcrypt was removed but can be installed using pecl.

**Comment by ezp127** [comment]
After install `laravel4-php71-encrypter` I did the following: 

- Create a new file in the `/bootstrap` folder called `illuminate-fundation-start.php`.
- Copy the content of `vendor/laravel/framework/src/Illuminate/Foundation/start.php` to the file above.
- Comment or remove: 
```
# if ( ! extension_loaded('mcrypt'))
# {
# 	echo 'Mcrypt PHP extension required.'.PHP_EOL;

# 	exit(1);
# }
```
- Change `/bootstrap/start.php` to:
```
# require $framework.'/Illuminate/Foundation/start.php';
require $app['path.base'].'/bootstrap/illuminate-foundation-start.php';
```

I also removed the commands from `post-install-cmd` and `post-update-cmd` in the `composer.json` that causes Mcrypt invocation:
```
	"scripts": {
		"post-install-cmd": [],
		"post-update-cmd": [],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
```

After this you should be able to use Artisan with PHP 7.1 without have to install mcrypt extension

---

Sorry for commenting a closed issue. Just thought it would be useful mention these details
