### ISSUE TITLE
can't integrate it to Laravel 4.2 hosted online

### ISSUE THREAD

**Issue by blacklionxs** [tomgrohl/laravel4-php71-encrypter#9]
Hi thank's for the encrypter. How can i integrate this and make it work with my website (Laravel 4.2) hosted online on Hostinger ? i'm beginner

**Comment by tomgrohl** [comment]
Hi

Please follow the installation instructions [here](https://github.com/tomgrohl/laravel4-php71-encrypter/blob/1.1/README.md).

If your new to Laravel I would probably look at getting this to work locally first.

I'm not familar with Hostinger so I can't help you with that.
